-- DEFINE LAST_NAME  = '';
-- DEFINE FIRST_NAME = '';
-- DEFINE EMAIL      = '';
-- DEFINE USER_NAME  = '';
-- DEFINE PWD_HASH   = '';

INSERT INTO PROVIDER (
  ORGANIZATION_ID, USER_TYPE_ID, USER_ROLE_ID, LAST_NAME, FIRST_NAME, EMAIL, IS_ACTIVE
) VALUES (
  '06', '03', '06', '&&LAST_NAME', '&&FIRST_NAME', '&&EMAIL', 1
);

INSERT INTO AUTH_USER_CREDENTIALS (
  ORGANIZATION_ID, COMMON_USER_ID, COMMON_USERNAME, PASSWORD, NAME
) VALUES (
  '06', (SELECT ID FROM PROVIDER WHERE EMAIL = '&&EMAIL'), '&&USER_NAME', '&&PWD_HASH', '&&EMAIL'
);

INSERT INTO AUTH_USER_ROLE (
  USER_ROLE_ID, USER_CREDENTIAL_ID
) VALUES (
  '06', (SELECT ID FROM AUTH_USER_CREDENTIALS WHERE COMMON_USERNAME = '&&EMAIL')
);

--COMMIT;
